### ISSUE TITLE
compnerd/gha-setup-swift is consistently faster on Windows.

### ISSUE THREAD

**Issue by dabrahams** [SwiftyLab/setup-swift#233]
When I use this plugin with Swift 5.9, it usually takes about 2 minutes 20 seconds.  With https://github.com/compnerd/gha-setup-swift it's more like 1 minute 40 seconds.  Maybe there are some tricks in that plugin you could steal?

**Comment by soumyamahunt** [comment]
I am not familiar with Swift on Windows that much, most of what I implemented using Official docs and help from community members like @stevapple. I am welcome for contributions in this feature.

**Comment by dabrahams** [comment]
Maybe after #236 is addressed; until then I am using other action implementations.

**Comment by soumyamahunt** [comment]
@dabrahams [latest release](https://github.com/SwiftyLab/setup-swift/releases/tag/v1.6.0) fixes caching which should improve speed across all the runners (might be faster than the action linked). However the first run speed might be slower as this action provides additional functionalities like determining toolchain based on provided semver, caching etc. which are not available in the action you have linked (at least from the documentation what I can interpret).

You can run this action on your default branch once to generate reusable caches across all branches. You can also disable caching to get speed closer to the action linked above.

**Comment by dabrahams** [comment]
Wonderful!  Thanks for supporting this action so well.  Deeply appreciated.
