### ISSUE TITLE
Link failures in CI when I use this action

### ISSUE THREAD

**Issue by dabrahams** [SwiftyLab/setup-swift#236]
With this action I get link errors in CI (failure to find a Foundation symbol!) that I don't get if I use swift-actions/setup-swift@v1 instead.  I think you must be setting something up incorrectly.

```
Building for debugging...
dyld[7460]: Symbol not found: (_$s10Foundation11JSONDecoderC6decode_4fromxxm_AA4DataVtKSeRzlFTj)
  Referenced from: '/Users/runner/work/hylo/hylo/hylo/.build/plugins/tools/debug/GenerateHyloFileTests'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation'
[5/14] Generating HyloFileTests.swift
Error: Process completed with exit code 1.
```

The complete log of my failing build is 
[here](https://github.com/SwiftyLab/setup-swift/files/14502103/2_Native.macos-latest_debug.txt).

**Comment by soumyamahunt** [comment]
This is strange, never faced any linker errors in my repos where I am using this action. Would love feedback on what is being set as wrong, macOS specific implementation can be found [here](https://github.com/SwiftyLab/setup-swift/blob/main/src/installer/xcode.ts).

**Comment by dabrahams** [comment]
I have no idea; I've never written a GitHub action and wouldn't know what this source means.  I'd compare the code of the two actions if I were you to look for likely culprits.

**Comment by dabrahams** [comment]
As you can see from the build results on the  commit referenced above, that link error is not reproducing, so I'm going to close this issue.  Thanks for your attention!

**Comment by soumyamahunt** [comment]
Glad to know @dabrahams you got this resolved.
