### ISSUE TITLE
[Bug] Installing 5.10 (not 5.10.0) fails now that Swift 5.10.1 is released

### ISSUE THREAD

**Issue by dabrahams** [SwiftyLab/setup-swift#315]
See https://github.com/hylo-lang/hylo/actions/runs/10908612094/job/30274991314#step:4:1

**Comment by soumyamahunt** [comment]
@dabrahams  I am looking into the caching breaking for newer Xcode toolchains, meanwhile you can disable caching for now.

**Comment by dabrahams** [comment]
Oh.  If I just delete the old caches will that fix it, or do I actually need to disable them?  And how do I disable the cache for this action?  I don't see anything in the README

**Comment by dabrahams** [comment]
Never mind; I see it here.

**Comment by soumyamahunt** [comment]
> Oh. If I just delete the old caches will that fix it, or do I actually need to disable them?

Just deleting will result in immediate workflow to succeed but since it will generate new cache that will fail subsequent workflows.

> And how do I disable the cache for this action? I don't see anything in the README

The inputs are documented in `action.yml` file, and `README` does mention to go through this file for list of inputs supported. The input name is `cache-snapshot`.

**Comment by dabrahams** [comment]
[That](https://github.com/hylo-lang/Durian/pull/4/files)…
[didn't work](https://github.com/hylo-lang/hylo/actions/runs/10925820513/job/30328236268#step:4:82)

**Comment by soumyamahunt** [comment]
> [That](https://github.com/hylo-lang/Durian/pull/4/files)… [didn't work](https://github.com/hylo-lang/hylo/actions/runs/10925820513/job/30328236268#step:4:82)

Did you try deleting the cache and running the action with `cache-snapshot` `false` or without deleting the cache?
I think deleting the cache and running with `cache-snapshot` `false` should work.

**Comment by dabrahams** [comment]
Yes, deleting the caches works, thanks.  IMO it's a bug, or at least extremely hard to use, that the cache gets used when `cache-snapshot` is `false`, but that's for you to decide.

**Comment by soumyamahunt** [comment]
@dabrahams can you try reenabling `cache-snapshot` to `true` and run your workflow twice (second trigger started once first is completed). 

I am no longer able to reproduce this in my CI, now I am under the impression that this might be some issue from GitHub end.

**Comment by dabrahams** [comment]
I can try; that will take some considerable time FWIW.

**Comment by soumyamahunt** [comment]
> I can try; that will take some considerable time FWIW.

I think you can ignore this, the issue seems to only affect `macos-13` runner.

**Comment by dabrahams** [comment]
Well, the jobs are re-running now. In case you're interested: https://github.com/hylo-lang/hylo/actions/runs/10927463998?pr=1597

**Comment by dabrahams** [comment]
The second run with cache enabled worked. What does that mean?

**Comment by soumyamahunt** [comment]
> The second run with cache enabled worked. What does that mean?

The issue is due to from 5.10.1 macOS toolchain installation caching breaks across machine architecture, i.e action caches created from m series runners fail on intel machine and vice-versa. Next release will fix this issue.

**Comment by soumyamahunt** [comment]
@dabrahams fix has been released: https://github.com/SwiftyLab/setup-swift/releases/tag/v1.8.0
