### ISSUE TITLE
[Bug] Installer not working correctly when used with Act locally

### ISSUE THREAD

**Issue by tomwyr** [SwiftyLab/setup-swift#331]
- [x] I have gone through the action [README](https://github.com/SwiftyLab/setup-swift/blob/main/README.md), [documentation](https://github.com/SwiftyLab/setup-swift/blob/main/action.yml) and [wiki](https://github.com/SwiftyLab/setup-swift/wiki).
- [x] I don't see my issue listed in [existing issues](https://github.com/SwiftyLab/setup-swift/issues).

**Describe the bug**
When using the action locally with Act, it fails to restore cache after running the action for the second and consecutive times.
The action seems to be mistakenly clearing the cache in the process.

**To Reproduce**
- Install [Act](https://github.com/nektos/act).
- Setup a workflow that only installs Swift.
- Run the workflow with `act -j setup-swift` for the first time - action installs toolchain correctly.
- Run the workflow second time - action fails to restore cache and find Swift in path.

```
name: Setup Swift

on:
  push:
    branches:
      - main

jobs:
  setup-swift:
    runs-on: ubuntu-22.04
    steps:
      - uses: SwiftyLab/setup-swift@latest
```

**Expected behavior**
Action restores cached Swift toolchain and adds it to path.

**Logs**
[first-run.txt](https://github.com/user-attachments/files/17644931/first.txt)
[second-run.txt](https://github.com/user-attachments/files/17644933/second.txt)

**Runner (please complete the following information):**
 - Name: ubuntu-22.04
 - OS: Ubuntu
 - Version 22.04

**Additional context**
Based on the logs and looking through the sources, what I noticed is:
- Action gets Swift location in tool-cache [src](https://github.com/SwiftyLab/setup-swift/blob/main/src/installer/base.ts#L52)
- Action reaches the line where it starts the cache restoration process [src](https://github.com/SwiftyLab/setup-swift/blob/main/src/installer/base.ts#L76)
- Tool-cache prepares the cache installation location by removing existing files at the destination path [src](https://github.com/actions/toolkit/blob/main/packages/tool-cache/src/tool-cache.ts#L673)
- Because the source and the target destinations are the same, what effectively happens is tool-cache removes cached files first and tries to copy non-existent files to the same location [src](https://github.com/actions/toolkit/blob/main/packages/tool-cache/src/tool-cache.ts#L438)

**Comment by soumyamahunt** [comment]
@tomwyr can you try with #332 if it fixes your issue?

**Comment by tomwyr** [comment]
@soumyamahunt It did fix the problem. Below are updated logs from the second, now successful, action execution.

[second-success.txt](https://github.com/user-attachments/files/17659383/second-success.txt)
