### ISSUE TITLE
`v1` branch/tag for the latest release

### ISSUE THREAD

**Issue by stevapple** [SwiftyLab/setup-swift#68]
This can be useful for users who want the latest features and fixes, and don’t want to manually bump the version all the time.

**Comment by soumyamahunt** [comment]
Currently action has a `latest` tag, which points to the latest version. The reason I chose `latest` instead of `v1` is I didn't want [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) to update action based on semver.

**Comment by stevapple** [comment]
Well I think some users might be hesitant because `latest` doesn’t guarantee API compatibility in any means but `v1` generally does.

**Comment by stevapple** [comment]
Does it mean the action **doesn’t guarantee** any kind of API compatibility, or it provides API compatibility **forever**? I don’t think either of them is viable…

**Comment by soumyamahunt** [comment]
Action will be providing API compatibility, I don't see any reason to introduce any breaking change to API, but I am also considering adding `v{major}` tag as well. 

This can be added similar to how latest tag is updated currently with additional logic for detecting major version:

https://github.com/SwiftyLab/setup-swift/blob/5dfc5184796ead5ef4e3ce6bae9ba37ea8049151/.github/workflows/main.yml#L514-L518

Do you want to have a crack at this?
